services:
  tms:
    build: .
    container_name: tms
    depends_on: 
      - tms-postgres
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tms-postgres:5432/tms
      - SPRING_DATASOURCE_USERNAME=tms
      - SPRING_DATASOURCE_PASSWORD=tms
    restart: unless-stopped
  tms-postgres:
    image: postgres:15-alpine
    container_name: tms-postgres
    environment:
      - POSTGRES_PASSWORD=tms
      - POSTGRES_USER=tms
      - POSTGRES_DB=tms
    ports:
      - 5432:5432
    restart: unless-stopped