create table if not exists users 
(
	id bigint generated by default as identity primary key,
	email varchar(64) not null,
	name varchar(64)
);

create table if not exists task
(
	id bigint generated by default as identity primary key,
	name varchar(128) not null,
	description text,
	status varchar(16) not null,
	priority varchar(16) not null,
	author_id bigint not null references users,
	responsible_id bigint not null references users
);